# Generated by Django 5.1.4 on 2025-01-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_url', models.CharField(max_length=200)),
                ('short_url', models.CharField(max_length=50)),
                ('checks', models.BigIntegerField(default=0)),
            ],
        ),
    ]
